.PHONY: clean All

All:
	@echo "----------Building project:[ app - Debug ]----------"
	@"$(MAKE)" -f  "app.mk"
clean:
	@echo "----------Cleaning project:[ app - Debug ]----------"
	@"$(MAKE)" -f  "app.mk" clean
